#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Detects Unity installation path and generates UnityPath.props.

.DESCRIPTION
    This script extracts the Unity installation path from Unity-generated csproj file
    and creates UnityPath.props for use by VoiceLiveAPI.Unity project.

    The generated UnityPath.props eliminates the need for UNITY_PATH environment variable.

.PARAMETER ProjectRoot
    Root directory of VoiceLiveAPI-Libs. Defaults to parent of script directory.

.EXAMPLE
    ./Setup-UnityPath.ps1

.EXAMPLE
    ./Setup-UnityPath.ps1 -ProjectRoot "C:\path\to\VoiceLiveAPI-Libs"

.NOTES
    Prerequisites:
    - Unity Editor must have opened the Unity project at least once
    - This generates Com.Reseul.Azure.AI.VoiceLiveAPI.Unity.csproj
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"

# Path definitions
$UnityProjectRoot = Join-Path $ProjectRoot "..\Unity\UnityVoiceLiveAPI"
$UnityCsproj = Join-Path $UnityProjectRoot "Com.Reseul.Azure.AI.VoiceLiveAPI.Unity.csproj"
$OutputPropsFile = Join-Path $ProjectRoot "VoiceLiveAPI.Unity\UnityPath.props"

Write-Host ""
Write-Host "=== Unity Path Setup ===" -ForegroundColor Cyan
Write-Host ""

# Resolve paths
try {
    $UnityProjectRoot = Resolve-Path $UnityProjectRoot -ErrorAction Stop
    Write-Host "Unity project: $UnityProjectRoot" -ForegroundColor Gray
} catch {
    Write-Error "Unity project directory not found: $UnityProjectRoot"
    exit 1
}

# Check Unity-generated csproj
if (-not (Test-Path $UnityCsproj)) {
    Write-Host ""
    Write-Host "ERROR: Unity-generated csproj not found" -ForegroundColor Red
    Write-Host ""
    Write-Host "Expected: $UnityCsproj" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Please open the Unity project with Unity Editor first:" -ForegroundColor White
    Write-Host "  1. Open Unity Hub" -ForegroundColor Gray
    Write-Host "  2. Open project: $UnityProjectRoot" -ForegroundColor Gray
    Write-Host "  3. Wait for Unity to generate project files" -ForegroundColor Gray
    Write-Host "  4. Run this script again" -ForegroundColor Gray
    Write-Host ""
    exit 1
}

Write-Host "Found csproj: $UnityCsproj" -ForegroundColor Green

# Extract Unity path from csproj
$content = Get-Content $UnityCsproj -Raw
$match = [regex]::Match($content, 'HintPath>(.+?)\\Editor\\Data\\Managed')

if (-not $match.Success) {
    Write-Error "Could not extract Unity path from csproj. The file format may have changed."
    exit 1
}

$unityPath = $match.Groups[1].Value

# Validate the extracted path
if (-not (Test-Path $unityPath)) {
    Write-Host ""
    Write-Host "WARNING: Extracted Unity path does not exist" -ForegroundColor Yellow
    Write-Host "Path: $unityPath" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "This may happen if Unity was uninstalled or moved." -ForegroundColor Gray
    Write-Host "The props file will still be generated, but builds may fail." -ForegroundColor Gray
    Write-Host ""
}

Write-Host "Detected Unity: $unityPath" -ForegroundColor Green

# Ensure output directory exists
$outputDir = Split-Path -Parent $OutputPropsFile
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Generate UnityPath.props
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$propsContent = @"
<Project>
  <!--
    Auto-generated by Setup-UnityPath.ps1 at $timestamp
    Do not edit manually. Regenerate with: pwsh scripts/Setup-UnityPath.ps1
  -->
  <PropertyGroup>
    <UNITY_PATH>$unityPath</UNITY_PATH>
  </PropertyGroup>
</Project>
"@

$propsContent | Out-File -FilePath $OutputPropsFile -Encoding UTF8
Write-Host "Generated: $OutputPropsFile" -ForegroundColor Green

Write-Host ""
Write-Host "=== Setup Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "You can now build with:" -ForegroundColor White
Write-Host "  dotnet build VoiceLiveAPI.Unity" -ForegroundColor Gray
Write-Host ""
